---
- name: Install a list of packages
  apt:
    name: "{{ install_packages }}"
    state: latest
  vars:
    install_packages:
    - bash-completion
    - code
    - curl
    - docker-compose
    - docker.io
    - flameshot
    - git
    - golang-go
    - google-chrome-stable
    - kubectl
    - network-manager-fortisslvpn-gnome
    - nmap
    - ntp
    - openssh-server
    - python-apt
    - python-setuptools
    - python3-boto3
    - python3-botocore
    - python3-pip
    - python3-setuptools
    - python3-winrm
    - rdesktop
    - remmina
    - remmina-plugin-rdp
    - shellcheck
    - software-properties-common
    - terminator
    - traceroute
    - tree
    - unetbootin
    - vim
    - virtualbox-6.0
    - whois
  tags:
    - packages

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest


- name: remove packages
  apt:
    name: "{{ remove_packages }}"
    state: absent
  vars:
    remove_packages:
    - thunderbird
    - thunderbird-gnome-support
    - thunderbird-locale-en
    - thunderbird-locale-en-us
    - thunderbird-locale-pt
    - thunderbird-locale-pt-br
    - transmission-common
    - transmission-gtk
